rti/dashboard/forms.py
import os
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, SubmitField, FileField, \
    DateField, TelField, SelectField, IntegerField, FieldList, DateTimeField
from wtforms.validators import DataRequired, Email, ValidationError, NumberRange
from rti.models import User

typePiece = [('Passeport', 'Passeport'),
             ('Visa', 'Visa'),
             ("carte d'identité nationale", "carte d'identité nationale"),
             ('carte de residence permanante', "carte de residence permanante")
             ]


class NewAdminForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    prenom = StringField('Prenom', validators=[DataRequired()])
    date_nais = DateField("Date de naissance", format="%Y-%m-%d", validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    # password = PasswordField('Mot de passe', validators=[DataRequired()])
    tel = TelField('Numero de téléphone', validators=[DataRequired()])
    type_piece = SelectField("Type de piece d'identité", validators=[DataRequired()], choices=typePiece)
    profile = SelectField("Rôle à jouer", validators=[DataRequired()], choices=[])
    num_piece = StringField("Numero de piece d'identité", validators=[DataRequired()])
    photo_piece = FileField("Photo de piece d'identité", validators=[DataRequired(), FileAllowed(['jpg', 'jpeg','png'], message="Elle doit être de forma :[jpg/jpeg/png]")])
    avatar = FileField("Avatar", validators=[FileAllowed(['jpg', 'jpeg', 'png'], message="Elle doit être de forma :[jpg/jpeg/png]")])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Il y a déja un compte relié à ce mail')


class UpdateInformAdmin(FlaskForm):
    nom = StringField('nom', validators=[DataRequired()])
    prenom = StringField('prenom', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    date_nais = DateField("Date de naissance", format="%Y-%m-%d", validators=[DataRequired()])
    tel = TelField('Numero de téléphone', validators=[DataRequired()])
    type_piece = SelectField("Type de piece d'identité", validators=[DataRequired()], choices=typePiece)
    num_piece = StringField("Numero de piece d'identité", validators=[DataRequired()])
    photo_piece = FileField("Photo de piece d'identité", validators=[FileAllowed(['jpg', 'jpeg', 'heic', 'png'], message="Elle doit être de forma :[jpg/jpeg/png]")])
    avatar = FileField('Modifier la piece', validators=[FileAllowed(['jpg', 'jpeg', 'heic', 'png'])])
    password = PasswordField('Password')
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Enregistrer')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('Cet email est déja enregistré. Veuillez en choisir un autre')


# Formulaire de Duree
class DureeForm(FlaskForm):
    libelle = SelectField('Duree', choices=[], validators=[DataRequired()])


# Formulaire de Taux
class TauxForm(FlaskForm):
    montant = IntegerField('Taux', validators=[DataRequired()])


# Formulaire de retrait
class ForfaitForm(FlaskForm):
    libelle = StringField('Libelle', validators=[DataRequired()])
    borne_inf = IntegerField('Montant inferieur', validators=[DataRequired(), NumberRange(min=10000)])
    borne_sup = IntegerField('Montant Supperieur', validators=[DataRequired(), NumberRange(min=10000)])
    taux = FieldList(IntegerField('Taux', validators=[DataRequired(), NumberRange(min=1, max=100)]), min_entries=1)
    duree = FieldList(SelectField('Duree', choices=[], validators=[DataRequired()]), min_entries=1)
    submit = SubmitField('Valider')

# Formulaire d'investissement
class InvestmentForm(FlaskForm):
    montant = IntegerField('Montant', validators=[DataRequired()])
    actif = IntegerField('Actif', validators=[DataRequired()])
    date = DateTimeField("date d'investissement", validators=[DataRequired()])
    forfait = SelectField('Choisir', validators=[DataRequired()])
    submit = SubmitField('Valider')


# Formulaire de retrait
class WithdrawalForm(FlaskForm):
    montant = IntegerField('Montant', validators=[DataRequired()])
    justificatif = StringField('justificatif', validators=[DataRequired()])
    date = DateField("date d'investissement", validators=[DataRequired()])
    submit = SubmitField('Valider')


# pour forfait et duré
class GenerateForm(FlaskForm):
    nombre = IntegerField("Nombre", validators=[DataRequired(), NumberRange(min=1, max=10)])
    duree = SelectField("Duree", choices=[('MOIS', 'MOIS'), ('AN', 'AN')], validators=[DataRequired()])


def removeFile(filename):
    if os.path.exists('rti/static/img/avatar/'+ filename):
        return os.remove('rti/static/img/avatar/'+ filename)
    else:
        return "Impossible de supprimer le fichier car il n'existe pas"

rti/dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

rti/dashboard/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from rti import bcrypt, db
from rti.dashboard import dashboard
from rti.dashboard.forms import NewAdminForm, UpdateInformAdmin, removeFile, ForfaitForm, DureeForm
from rti.dashboard.utils import save_file, send_welcome_email, insertToDB, get_roles
from rti.models import User, load_profil, load_all_admin, load_user, load_all_profil, Profil, Forfait, Taux, Duree
from rti.dashboard.forms import GenerateForm
from rti.security.utils import save_piece_form


# ========================= USER =================================
@dashboard.route('/new/admin', methods=['GET', 'POST'])
@dashboard.route('/new/client', methods=['GET', 'POST'])
@login_required
def user_new():
    form = NewAdminForm()
    url = ""
    role = []
    profil = Profil()
    if str(request.url_rule) == "/new/admin":
        url = 'dashboard/admin/new.html'
        role = get_roles()
    elif str(request.url_rule) == "/new/client":
        profil = load_profil('CLIENT')
        url = 'dashboard/client/new.html'
        role = [(role.id, role.libelle) for role in Profil.query.filter_by(libelle="CLIENT")]

    form.profile.choices = role
    if form.validate_on_submit():
        if str(request.url_rule) == "/new/admin":
            profil = Profil.query.get(int(form.profile.data))

        passwordGenerated = datetime.now().strftime("%H%M%H%M%S")
        hashed_password = bcrypt.generate_password_hash(passwordGenerated).decode('utf-8')
        picture_file = save_piece_form(form.photo_piece.data)
        user = User()
        user.nom = form.nom.data
        user.prenom = form.prenom.data
        user.date_nais = form.date_nais.data
        user.password = hashed_password
        user.tel = form.tel.data
        user.email = form.email.data
        user.type_piece = form.type_piece.data
        user.num_piece = form.num_piece.data
        user.photo_piece = picture_file
        user.profil = profil
        if form.avatar.data:
            user.avatar = save_piece_form(form.avatar.data)
        insertToDB([user])
        send_welcome_email(user)
        print(passwordGenerated)
        if str(request.url_rule) == "/new/admin":
            flash('Nouvel administrateur ajouté avec succès. Un email lui a été envoyé pour qu\'il puisse se connecter',
                  'success')
            return redirect(url_for('dashboard.admin_list'))
        else:
            flash('Nouveau client ajouté avec succès !', 'success')
            return redirect(url_for('dashboard.client_list'))

    return render_template(url, form=form, user=current_user)


@dashboard.route('/profile/admin/<int:id>', methods=['GET', 'POST'])
@dashboard.route('/profile/admin', methods=['GET', 'POST'])
@login_required
def edit_user(id=None):
    user = User()
    url = ""
    if id:
        user = load_user(int(id))
        url = 'dashboard/client/edit.html'
    else:
        user = current_user
        url = 'dashboard/admin/edit.html'

    form = UpdateInformAdmin(obj=user)
    if form.validate_on_submit():
        user.nom = form.nom.data
        user.prenom = form.prenom.data
        user.email = form.email.data
        user.tel = form.tel.data
        user.num_piece = form.num_piece.data
        user.type_piece = form.type_piece.data

        if form.password.data != '':
            if form.password.data == form.confirm_password.data:
                user.password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                flash(
                    'La modification du mot de passe n\'a pas été pris en compte car les mots de passe ne correspondent pas.',
                    'danger')
        if form.avatar.data:
            user.avatar = save_piece_form(form.avatar.data)
        if form.photo_piece.data:
            user.photo_piece = save_piece_form(form.photo_piece.data)
        db.session.commit()
        flash('Données modifiées avec succès', 'success')
        return redirect(url_for('dashboard.edit_user'))
    return render_template(url, form=form, user=user)


@dashboard.route('/block/user/<int:id>', methods=['GET', 'POST'])
@login_required
def block_user(id):
    user = load_user(int(id))
    if current_user.profil.libelle == "ADMIN":
        print(current_user.profil.libelle)
        if user.blocked:
            user.blocked = False
            db.session.commit()
            flash('Le compte à été Débloqué', 'success')
            return redirect(url_for('dashboard.admin_list'))
        else:
            user.blocked = True
            print('false')
            db.session.commit()
            flash('Le compte à été bloqué', 'danger')
            return redirect(url_for('dashboard.admin_list', user=current_user))
    else:
        flash('L\'administrateur seul à se droit', 'danger')
    return render_template('dashboard/admin/index.html', user=current_user, admins=load_all_admin())


@dashboard.route('/delete/user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    try:
        user = load_user(int(id))
        removeFile(user.photo_piece)
        removeFile(user.avatar)
        db.session.delete(user)
        db.session.commit()
        if user.profil.libelle == "ADMIN" or user.profil.libelle == "COMPTABLE":
            flash('Administrateur supprimé avec succès', 'success')
        else:
            flash('Client supprimé avec succès', 'success')
            return redirect(url_for('dashboard.client_list'))
    except:
        flash('Impossible de supprimer l\'admin', 'error')
        return redirect(url_for('dashboard.admin_list'))


# ========================= ADMIN AND ACCOUNTING =================================
@dashboard.route('/list/admin')
@login_required
def admin_list():
    return render_template('dashboard/admin/index.html', user=current_user, admins=load_all_admin())


# ========================= CLIENT =================================
@dashboard.route('/list/client')
@login_required
def client_list():
    clients = User.query.all()
    return render_template('dashboard/client/list.html', user=current_user, clients=clients)


# ========================= OTHERS =================================
@dashboard.route('/delete/other/<int:id>', methods=['GET', 'POST'])
@login_required
def other_delete(id):
    pass


# ========================= TAUX & DUREE =================================
@dashboard.route('/list/taux-duree/<int:id>')
@dashboard.route('/list/taux-duree')
@login_required
def taux_duree_list(id=None):
    duree = Duree.query.all()
    taux = Taux.query.all()
    form = GenerateForm()
    if form.validate_on_submit():
        print(form.data)
    return render_template('dashboard/tauxduree/list.html', formDuree=form, user=current_user, duree=duree, taux=taux)


@dashboard.route('/add/duree', methods=['GET', 'POST'])
@login_required
def addDuree():

    if request.method == "POST":
        if request.form.get('nombre'):
            nombre = request.form.get('nombre')
            duree = request.form.get('duree')
            libelle = nombre + ' ' + duree
            if Duree.query.filter_by(libelle=libelle).first():
                flash('Cette durée existe déjà, changer s\'il vous plaît !', category='danger')
            else:
                duree = Duree(libelle=libelle)
                insertToDB([duree])
    return redirect(url_for('dashboard.forfait_new'))


# ========================= FORFIAT =================================
@dashboard.route('/list/forfait')
@login_required
def forfait_list():
    forfaits = Forfait.query.all()
    return render_template('dashboard/forfait/list.html', user=current_user, forfaits=forfaits)


@dashboard.route('/new/forfait', methods=['GET', 'POST'])
@login_required
def forfait_new():
    form = ForfaitForm(request.form)
    formDuree = GenerateForm()
    countDuree = Duree.query.all()

    print(request.data)

    form.duree.min_entries = Duree.query.count()
    form.taux.min_entries = Duree.query.count()
    if not form.libelle.data:
        form.process()
    for dure in form.duree:
        dure.choices = [(role.id, role.libelle) for role in Duree.query.all()]
    if form.validate_on_submit():
        count = 0
        if Forfait.query.filter_by(libelle=form.libelle.data).first():
            flash(('Ce Forfait existe déjà, changer s\'il vous plaît !'), category='danger')
        else:
            forfait = Forfait(libelle=form.libelle.data, borne_inf=form.borne_inf.data, borne_sup=form.borne_sup.data)
            db.session.add(forfait)
            for cpt in form.duree.data:
                duree = Duree.query.get(int(cpt))
                taux = Taux(taux_interet=form.taux.data[count], forfait=forfait, duree=duree)
                db.session.add(taux)
                print(form.taux.data)
                count += 1
            db.session.commit()
            flash(('Forfait ajouté avec succes !'), category='success')
            return redirect('/list/forfait')
    return render_template('dashboard/forfait/new.html', formDuree=formDuree, duree=countDuree, form=form,
                           user=current_user)


@dashboard.route('/edit/<int:id>', methods=['GET', 'POST'])
def forfait_edit(id):
    print(id)
    # return render_template('dashboard/forfait/edit.html', user=current_user)
    return "{}".format(id)


@dashboard.route('/delete/<int:id>', methods=['GET', 'POST'])
def forfait_delete(id):
    return "{}".format(id)


# ========================= RETRAIT =================================
@dashboard.route('/admin/new/forfait')
def retrait_new():
    return render_template('dashboard/forfait/new.html', user=current_user)


@dashboard.route('/admin/list/forfait')
def retrait_list():
    return render_template('dashboard/forfait/list.html', user=current_user)


@dashboard.route('/admin/edit/forfait')
def retrait_edit():

rti/templates/dashboard/admin/index.html
{% extends 'dashboard/base.html' %}
{% block title2 %}Liste des employés{% endblock %}
{% block title3 %}<i class="bi bi-person-lines-fill icon-title-color"></i> Les administrateurs {% endblock %}

{% block content %}
<!-- Container-fluid starts-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card" style="padding:20px">
                <div class="card-header" >
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <h5 class="text-center">ADMINISTRATEURS <br>
                                [COMPTABLES / ADMINS]</h5>
                        </div>
                        <div class="col-12 col-md-6 text-end">

                            <a class=" btn-new-user" href="/new/admin">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
                                    <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
                                    <path d="M224 256c70.7 0 128-57.31 128-128S294.7 0 224 0C153.3 0 96 57.31 96 128S153.3 256 224 256zM274.7 304H173.3C77.61 304 0 381.6 0 477.3C0 496.5 15.52 512 34.66 512h378.7C432.5 512 448 496.5 448 477.3C448 381.6 370.4 304 274.7 304zM616 200h-48v-48C568 138.8 557.3 128 544 128s-24 10.75-24 24v48h-48C458.8 200 448 210.8 448 224s10.75 24 24 24h48v48C520 309.3 530.8 320 544 320s24-10.75 24-24v-48h48C629.3 248 640 237.3 640 224S629.3 200 616 200z"/>
                                </svg>
                                 <span>Ajouter admin</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="display mb-5" id="advance-1">
                            <thead>
                            <tr>
                                <th>Image</th>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Email</th>
                                <th>Profil</th>
                                <th>Etat du compte</th>
                                <th>Supprimer</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for admin in admins %}
                            {% if (admin.profil.libelle == "ADMIN" or admin.profil.libelle == "COMPTABLE") and admin.email != user.email %}
                            <tr>
                                <td><img width="64" height="64" src="{{url_for('static', filename='img/avatar/'+ admin.avatar)}}" alt=""></td>
                                <td>{{ admin.nom }}</td>
                                <td>{{ admin.prenom }}</td>
                                <td>{{ admin.email }}</td>
                                <td>{{ admin.profil.libelle }}</td>
                                <td>
                                    {% if admin.blocked %}
                                        <a href="" class="btn btn-secondary btn-sm" onclick="
                                                        if(confirm('Etes vous sur de vouloir Déblocker ce compte ?'))
                                                        window.location = '{{ url_for('dashboard.block_user', id=admin.id) }}'; ">
                                        Bloqué <i class="bi bi-lock"></i>
                                    </a>
                                    {% else %}
                                        <a href="" class="btn btn-secondary btn-sm" onclick="
                                                        if(confirm('Etes vous sur de vouloir Bloquer ce compte ?'))
                                                        window.location = '{{ url_for('dashboard.block_user', id=admin.id) }}'; ">
                                        Débloqué <i class="bi bi-unlock"></i>
                                        </a>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="" class="btn btn-danger  btn-sm" onclick="
                                                        if(confirm('Etes vous sur de vouloir supprimer cet administrateur'))
                                                        window.location = '{{ url_for('dashboard.delete_user', id=admin.id) }}'; ">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                              {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends-->
{% endblock %}

rti/templates/dashboard/admin/new.html
{% extends 'dashboard/base.html' %}
{% block title2 %}Nouvel admin{% endblock %}
{% block title3 %} <i class="bi bi-person-plus icon-title-color"></i> Ajouter un admin {% endblock %}

{% block content %}
<!-- Container-fluid starts-->
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                        <div class="text-center">
                            <h5>NOUVEL ADMINISTRATEUR</h5>
                        </div>
                </div>
                <div class="card-body">
                    <form class="needs-validation" style="padding:20px;" novalidate="" method="POST" action="" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <div class="row g-3">
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.nom.label(class="form-label") }}
                                {{ form.nom(placeholder="Son nom", class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.nom.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.prenom.label(class="form-label") }}
                                {{ form.prenom(placeholder="Son prénom", class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.prenom.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.email.label(class="form-label") }}
                                {{ form.email(placeholder="Son email", class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.email.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.tel.label(class="form-label") }}
                                {{ form.tel(placeholder="Son numero de téléphone", class="form-control input-custom")
                                }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.tel.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.date_nais.label(class="form-label") }}
                                {{ form.date_nais(class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.date_nais.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.num_piece.label(class="form-label") }}
                                {{ form.num_piece(placeholder="Son numero de pièce", class="form-control input-custom")
                                }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.num_piece.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.profile.label(class="form-label") }}
                                {{ form.profile(class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.profile.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.type_piece.label(class="form-label") }}
                                {{ form.type_piece(class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.type_piece.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row g-3">
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.photo_piece.label(class="form-label") }}
                                {{ form.photo_piece(class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.photo_piece.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                {{ form.avatar.label(class="form-label") }}
                                {{ form.avatar(class="form-control input-custom") }}
                                <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                <div class="valid-feedback">Parfait!</div>
                                {% for message in form.avatar.errors %}
                                <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="form-check">
                                <div class="checkbox p-0">
                                    <input class="form-check-input" id="invalidCheck" type="checkbox" required="">
                                    <label class="form-check-label" for="invalidCheck">
                                        En ajoutant cet employé, je comprends lui donner accès total au
                                        tableau de bord.
                                    </label>
                                </div>
                                <div class="invalid-feedback">You must agree before submitting.</div>
                            </div>
                        </div>
                        <button class="btn btn-outline-success btn-lg w-100" type="submit">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends-->
{% endblock %}