rti/dashboard/forms.py
import os
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, SubmitField, FileField, \
    DateField, TelField, SelectField, IntegerField, FieldList, DateTimeField
from wtforms.validators import DataRequired, Email, ValidationError, NumberRange
from rti.models import User

typePiece = [('Passeport', 'Passeport'),
             ('Visa', 'Visa'),
             ("carte d'identité nationale", "carte d'identité nationale"),
             ('carte de residence permanante', "carte de residence permanante")
             ]


class NewAdminForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    prenom = StringField('Prenom', validators=[DataRequired()])
    date_nais = DateField("Date de naissance", format="%Y-%m-%d", validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    # password = PasswordField('Mot de passe', validators=[DataRequired()])
    tel = TelField('Numero de téléphone', validators=[DataRequired()])
    type_piece = SelectField("Type de piece d'identité", validators=[DataRequired()], choices=typePiece)
    profile = SelectField("Rôle à jouer", validators=[DataRequired()], choices=[])
    num_piece = StringField("Numero de piece d'identité", validators=[DataRequired()])
    photo_piece = FileField("Photo de piece d'identité", validators=[DataRequired(), FileAllowed(['jpg', 'jpeg','png'], message="Elle doit être de forma :[jpg/jpeg/png]")])
    avatar = FileField("Avatar", validators=[FileAllowed(['jpg', 'jpeg', 'png'], message="Elle doit être de forma :[jpg/jpeg/png]")])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Il y a déja un compte relié à ce mail')


class UpdateInformAdmin(FlaskForm):
    nom = StringField('nom', validators=[DataRequired()])
    prenom = StringField('prenom', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    date_nais = DateField("Date de naissance", format="%Y-%m-%d", validators=[DataRequired()])
    tel = TelField('Numero de téléphone', validators=[DataRequired()])
    type_piece = SelectField("Type de piece d'identité", validators=[DataRequired()], choices=typePiece)
    num_piece = StringField("Numero de piece d'identité", validators=[DataRequired()])
    photo_piece = FileField("Photo de piece d'identité", validators=[FileAllowed(['jpg', 'jpeg', 'heic', 'png'], message="Elle doit être de forma :[jpg/jpeg/png]")])
    avatar = FileField('Modifier la piece', validators=[FileAllowed(['jpg', 'jpeg', 'heic', 'png'])])
    password = PasswordField('Password')
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Enregistrer')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('Cet email est déja enregistré. Veuillez en choisir un autre')


# Formulaire de Duree
class DureeForm(FlaskForm):
    libelle = SelectField('Duree', choices=[], validators=[DataRequired()])


# Formulaire de Taux
class TauxForm(FlaskForm):
    montant = IntegerField('Taux', validators=[DataRequired()])


# Formulaire de retrait
class ForfaitForm(FlaskForm):
    libelle = StringField('Libelle', validators=[DataRequired()])
    borne_inf = IntegerField('Montant inferieur', validators=[DataRequired(), NumberRange(min=10000)])
    borne_sup = IntegerField('Montant Supperieur', validators=[DataRequired(), NumberRange(min=10000)])
    taux = FieldList(IntegerField('Taux', validators=[DataRequired(), NumberRange(min=1, max=100)]), min_entries=1)
    duree = FieldList(SelectField('Duree', choices=[], validators=[DataRequired()]), min_entries=1)
    submit = SubmitField('Valider')

# Formulaire d'investissement
class InvestmentForm(FlaskForm):
    montant = IntegerField('Montant', validators=[DataRequired()])
    actif = IntegerField('Actif', validators=[DataRequired()])
    date = DateTimeField("date d'investissement", validators=[DataRequired()])
    forfait = SelectField('Choisir', validators=[DataRequired()])
    submit = SubmitField('Valider')


# Formulaire de retrait
class WithdrawalForm(FlaskForm):
    montant = IntegerField('Montant', validators=[DataRequired()])
    justificatif = StringField('justificatif', validators=[DataRequired()])
    date = DateField("date d'investissement", validators=[DataRequired()])
    submit = SubmitField('Valider')


# pour forfait et duré
class GenerateForm(FlaskForm):
    nombre = IntegerField("Nombre", validators=[DataRequired(), NumberRange(min=1, max=10)])
    duree = SelectField("Duree", choices=[('MOIS', 'MOIS'), ('AN', 'AN')], validators=[DataRequired()])


def removeFile(filename):
    if os.path.exists('rti/static/img/avatar/'+ filename):
        return os.remove('rti/static/img/avatar/'+ filename)
    else:
        return "Impossible de supprimer le fichier car il n'existe pas"

rti/dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

rti/dashboard/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from rti import bcrypt, db
from rti.dashboard import dashboard
from rti.dashboard.forms import NewAdminForm, UpdateInformAdmin, removeFile, ForfaitForm, DureeForm
from rti.dashboard.utils import save_file, send_welcome_email, insertToDB, get_roles
from rti.models import User, load_profil, load_all_admin, load_user, load_all_profil, Profil, Forfait, Taux, Duree
from rti.dashboard.forms import GenerateForm
from rti.security.utils import save_piece_form


# ========================= USER =================================
@dashboard.route('/new/admin', methods=['GET', 'POST'])
@dashboard.route('/new/client', methods=['GET', 'POST'])
@login_required
def user_new():
    form = NewAdminForm()
    url = ""
    role = []
    profil = Profil()
    if str(request.url_rule) == "/new/admin":
        url = 'dashboard/admin/new.html'
        role = get_roles()
    elif str(request.url_rule) == "/new/client":
        profil = load_profil('CLIENT')
        url = 'dashboard/client/new.html'
        role = [(role.id, role.libelle) for role in Profil.query.filter_by(libelle="CLIENT")]

    form.profile.choices = role
    if form.validate_on_submit():
        if str(request.url_rule) == "/new/admin":
            profil = Profil.query.get(int(form.profile.data))

        passwordGenerated = datetime.now().strftime("%H%M%H%M%S")
        hashed_password = bcrypt.generate_password_hash(passwordGenerated).decode('utf-8')
        picture_file = save_piece_form(form.photo_piece.data)
        user = User()
        user.nom = form.nom.data
        user.prenom = form.prenom.data
        user.date_nais = form.date_nais.data
        user.password = hashed_password
        user.tel = form.tel.data
        user.email = form.email.data
        user.type_piece = form.type_piece.data
        user.num_piece = form.num_piece.data
        user.photo_piece = picture_file
        user.profil = profil
        if form.avatar.data:
            user.avatar = save_piece_form(form.avatar.data)
        insertToDB([user])
        send_welcome_email(user)
        print(passwordGenerated)
        if str(request.url_rule) == "/new/admin":
            flash('Nouvel administrateur ajouté avec succès. Un email lui a été envoyé pour qu\'il puisse se connecter',
                  'success')
            return redirect(url_for('dashboard.admin_list'))
        else:
            flash('Nouveau client ajouté avec succès !', 'success')
            return redirect(url_for('dashboard.client_list'))

    return render_template(url, form=form, user=current_user)


@dashboard.route('/profile/admin/<int:id>', methods=['GET', 'POST'])
@dashboard.route('/profile/admin', methods=['GET', 'POST'])
@login_required
def edit_user(id=None):
    user = User()
    url = ""
    if id:
        user = load_user(int(id))
        url = 'dashboard/client/edit.html'
    else:
        user = current_user
        url = 'dashboard/admin/edit.html'

    form = UpdateInformAdmin(obj=user)
    if form.validate_on_submit():
        user.nom = form.nom.data
        user.prenom = form.prenom.data
        user.email = form.email.data
        user.tel = form.tel.data
        user.num_piece = form.num_piece.data
        user.type_piece = form.type_piece.data

        if form.password.data != '':
            if form.password.data == form.confirm_password.data:
                user.password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            else:
                flash(
                    'La modification du mot de passe n\'a pas été pris en compte car les mots de passe ne correspondent pas.',
                    'danger')
        if form.avatar.data:
            user.avatar = save_piece_form(form.avatar.data)
        if form.photo_piece.data:
            user.photo_piece = save_piece_form(form.photo_piece.data)
        db.session.commit()
        flash('Données modifiées avec succès', 'success')
        return redirect(url_for('dashboard.edit_user'))
    return render_template(url, form=form, user=user)


@dashboard.route('/block/user/<int:id>', methods=['GET', 'POST'])
@login_required
def block_user(id):
    user = load_user(int(id))
    if current_user.profil.libelle == "ADMIN":
        print(current_user.profil.libelle)
        if user.blocked:
            user.blocked = False
            db.session.commit()
            flash('Le compte à été Débloqué', 'success')
            return redirect(url_for('dashboard.admin_list'))
        else:
            user.blocked = True
            print('false')
            db.session.commit()
            flash('Le compte à été bloqué', 'danger')
            return redirect(url_for('dashboard.admin_list', user=current_user))
    else:
        flash('L\'administrateur seul à se droit', 'danger')
    return render_template('dashboard/admin/index.html', user=current_user, admins=load_all_admin())


@dashboard.route('/delete/user/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user(id):
    try:
        user = load_user(int(id))
        removeFile(user.photo_piece)
        removeFile(user.avatar)
        db.session.delete(user)
        db.session.commit()
        if user.profil.libelle == "ADMIN" or user.profil.libelle == "COMPTABLE":
            flash('Administrateur supprimé avec succès', 'success')
        else:
            flash('Client supprimé avec succès', 'success')
            return redirect(url_for('dashboard.client_list'))
    except:
        flash('Impossible de supprimer l\'admin', 'error')
        return redirect(url_for('dashboard.admin_list'))


# ========================= ADMIN AND ACCOUNTING =================================
@dashboard.route('/list/admin')
@login_required
def admin_list():
    return render_template('dashboard/admin/index.html', user=current_user, admins=load_all_admin())


# ========================= CLIENT =================================
@dashboard.route('/list/client')
@login_required
def client_list():
    clients = User.query.all()
    return render_template('dashboard/client/list.html', user=current_user, clients=clients)


# ========================= OTHERS =================================
@dashboard.route('/delete/other/<int:id>', methods=['GET', 'POST'])
@login_required
def other_delete(id):
    pass


# ========================= TAUX & DUREE =================================
@dashboard.route('/list/taux-duree/<int:id>')
@dashboard.route('/list/taux-duree')
@login_required
def taux_duree_list(id=None):
    duree = Duree.query.all()
    taux = Taux.query.all()
    form = GenerateForm()
    if form.validate_on_submit():
        print(form.data)
    return render_template('dashboard/tauxduree/list.html', formDuree=form, user=current_user, duree=duree, taux=taux)


@dashboard.route('/add/duree', methods=['GET', 'POST'])
@login_required
def addDuree():

    if request.method == "POST":
        if request.form.get('nombre'):
            nombre = request.form.get('nombre')
            duree = request.form.get('duree')
            libelle = nombre + ' ' + duree
            if Duree.query.filter_by(libelle=libelle).first():
                flash('Cette durée existe déjà, changer s\'il vous plaît !', category='danger')
            else:
                duree = Duree(libelle=libelle)
                insertToDB([duree])
    return redirect(url_for('dashboard.forfait_new'))


# ========================= FORFIAT =================================
@dashboard.route('/list/forfait')
@login_required
def forfait_list():
    forfaits = Forfait.query.all()
    return render_template('dashboard/forfait/list.html', user=current_user, forfaits=forfaits)


@dashboard.route('/new/forfait', methods=['GET', 'POST'])
@login_required
def forfait_new():
    form = ForfaitForm(request.form)
    formDuree = GenerateForm()
    countDuree = Duree.query.all()

    print(request.data)

    form.duree.min_entries = Duree.query.count()
    form.taux.min_entries = Duree.query.count()
    if not form.libelle.data:
        form.process()
    for dure in form.duree:
        dure.choices = [(role.id, role.libelle) for role in Duree.query.all()]
    if form.validate_on_submit():
        count = 0
        if Forfait.query.filter_by(libelle=form.libelle.data).first():
            flash(('Ce Forfait existe déjà, changer s\'il vous plaît !'), category='danger')
        else:
            forfait = Forfait(libelle=form.libelle.data, borne_inf=form.borne_inf.data, borne_sup=form.borne_sup.data)
            db.session.add(forfait)
            for cpt in form.duree.data:
                duree = Duree.query.get(int(cpt))
                taux = Taux(taux_interet=form.taux.data[count], forfait=forfait, duree=duree)
                db.session.add(taux)
                print(form.taux.data)
                count += 1
            db.session.commit()
            flash(('Forfait ajouté avec succes !'), category='success')
            return redirect('/list/forfait')
    return render_template('dashboard/forfait/new.html', formDuree=formDuree, duree=countDuree, form=form,
                           user=current_user)


@dashboard.route('/edit/<int:id>', methods=['GET', 'POST'])
def forfait_edit(id):
    print(id)
    # return render_template('dashboard/forfait/edit.html', user=current_user)
    return "{}".format(id)


@dashboard.route('/delete/<int:id>', methods=['GET', 'POST'])
def forfait_delete(id):
    return "{}".format(id)


# ========================= RETRAIT =================================
@dashboard.route('/admin/new/forfait')
def retrait_new():
    return render_template('dashboard/forfait/new.html', user=current_user)


@dashboard.route('/admin/list/forfait')
def retrait_list():
    return render_template('dashboard/forfait/list.html', user=current_user)


@dashboard.route('/admin/edit/forfait')
def retrait_edit():

rti/templates/dashboard/tauxduree/list.html
{% extends 'dashboard/base.html' %}
{% block title2 %}Liste des taux et durées {% endblock %}
{% block title3 %} <i class="bi bi-percent icon-title-color"></i> Durée & Taux{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title text-center mb-0">Liste des taux et leur durées</h4>
                <div class="card-options">
                    <a class="card-options-collapse" href="#" data-bs-toggle="card-collapse"
                       data-bs-original-title="" title=""><i class="fe fe-chevron-up"></i></a>
                    <a class="card-options-remove" href="#" data-bs-toggle="card-remove" data-bs-original-title=""
                        title=""><i class="fe fe-x"></i></a>
                </div>
            </div>
            <div class="table-responsive add-project">
                <table class="display mb-5" id="advance-1">
                    <thead>
                    <tr>
                        <th>Taux D'intérêt</th>
                        <th>Forfait</th>
                        <th>Durée</th>
                        <th class="text-center">Editer</th>
                        <th class="text-center">Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for t in  taux %}
                     <tr>
                        <td><a class="text-inherit" href="#" data-bs-original-title="" title="">{{ t.taux_interet | int }} %</a></td>
                        <td>{{ t.forfait.libelle }}</td>
                        <td>{{ t.duree.libelle }}</td>
                        <td class="text-center">
                            <a class="btn btn-primary btn-sm" href="{{ url_for('dashboard.forfait_edit', id=t.id) }}" >
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger btn-sm" href="javascript:void(0)"
                            onclick="if(confirm('Etes vous sur de vouloir supprimer ce forfait'))
                                    window.location = '{{ url_for('dashboard.forfait_delete', id=t.id) }}'; ">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                    <h4 class="card-title text-center mb-0">Liste des durées </h4>
                <div class="card-options">
                    <a class="card-options-collapse" href="#" data-bs-toggle="card-collapse"
                                             data-bs-original-title="" title=""><i class="fe fe-chevron-up"></i></a><a
                        class="card-options-remove" href="#" data-bs-toggle="card-remove" data-bs-original-title=""
                        title=""><i class="fe fe-x"></i></a>
                </div>
            </div>
            <div class="table-responsive add-project">
                <table class="display dataTable mb-5">
                    <thead>
                    <tr>
                        <th>Durée</th>
                        <th class="text-center">Editer</th>
                        <th class="text-center">Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for d in  duree %}
                     <tr>
                        <td><a class="text-inherit" href="#" data-bs-original-title="" title="">{{ d.libelle }}</a></td>
                        <td class="text-center">
                            <a class="btn btn-primary btn-sm"
                               href="{{ url_for('dashboard.taux_duree_list', id=d.id) }}"
                               data-bs-toggle="modal"
                               data-original-title="test" data-bs-target="#exampleModal"
                            >
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger btn-sm" href="javascript:void(0)"
                            onclick="if(confirm('Etes vous sur de vouloir supprimer ce forfait'))
                                    window.location = '{{ url_for('dashboard.forfait_delete', id=d.id) }}'; ">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog " role="document">
                            <form action="" method="post">
                                {{ formDuree.csrf_token() }}
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Nouvelle Durée</h5>
                                        <button class="btn-close" type="button" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    {{ formDuree.nombre.label(class="form-label") }}
                                                    {{ formDuree.nombre(class="form-control", value = (d.libelle[0] | int) ) }}
                                                    <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                                    <div class="valid-feedback">Parfait!</div>
                                                    {% for message in formDuree.nombre.errors %}
                                                    <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                                        {{ message }}
                                                    </div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    {{ formDuree.duree.label(class="form-label") }}
                                                    {{ formDuree.duree(class="form-control") }}
                                                    <div class="invalid-feedback">Veuillez remplir ce champ!</div>
                                                    <div class="valid-feedback">Parfait!</div>
                                                    {% for message in formDuree.duree.errors %}
                                                    <div class="border text-center text-danger bg-light p-2 mb-1 rounded">
                                                        {{ message }}
                                                    </div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer d-flex justify-content-between">
                                        <button class="new-btn btn-lg btn-primary" type="button"
                                                data-bs-dismiss="modal">Close
                                        </button>
                                        <button class="new-btn btn-lg btn-secondary" type="submit">Valider</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}